program PetiscoDashboard;

uses
  Forms,
  UnPetiscoDashboardView in 'UnPetiscoDashboardView.pas' {PetiscoDashBoardView},
  Componentes in 'src\Componentes.pas',
  UnProduto in 'src\UnProduto.pas',
  UnPetiscoDashBoardModelo in 'src\UnPetiscoDashBoardModelo.pas' {PetiscoDashBoardModelo: TDataModule},
  ProdutoAplicacao in 'src\ProdutoAplicacao.pas',
  UnProdutoListaRegistrosModelo in 'src\UnProdutoListaRegistrosModelo.pas',
  UnProdutoListaRegistrosView in 'src\UnProdutoListaRegistrosView.pas' {ProdutoListaRegistrosView},
  UnProdutoPesquisaModelo in 'src\UnProdutoPesquisaModelo.pas' {ProdutoPesquisaModelo},
  UnProdutoRegistroModelo in 'src\UnProdutoRegistroModelo.pas',
  UnProdutoRegistroView in 'src\UnProdutoRegistroView.pas' {ProdutoRegistroView},
  UnModelo in 'src\UnModelo.pas' {Modelo: TDataModule},
  UnClienteListaRegistrosView in 'src\UnClienteListaRegistrosView.pas' {ClienteListaRegistrosView},
  UnClienteListaRegistrosModelo in 'src\UnClienteListaRegistrosModelo.pas' {ClienteListaRegistrosModelo: TDataModule},
  UnClienteRegistroView in 'src\UnClienteRegistroView.pas' {ClienteRegistroView},
  UnClienteRegistroModelo in 'src\UnClienteRegistroModelo.pas' {ClienteRegistroModelo: TDataModule},
  ClienteAplicacao in 'src\ClienteAplicacao.pas',
  UnFornecedorListaRegistrosView in 'src\UnFornecedorListaRegistrosView.pas' {FornecedorListaRegistrosView},
  UnFornecedorListaRegistrosModelo in 'src\UnFornecedorListaRegistrosModelo.pas' {FornecedorListaRegistrosModelo: TDataModule},
  UnFornecedorRegistroModelo in 'src\UnFornecedorRegistroModelo.pas' {FornecedorRegistroModelo: TDataModule},
  UnFornecedorRegistroView in 'src\UnFornecedorRegistroView.pas' {FornecedorRegistroView},
  FornecedorAplicacao in 'src\FornecedorAplicacao.pas',
  CaixaAplicacao in 'src\CaixaAplicacao.pas',
  UnCaixaMenuView in 'src\UnCaixaMenuView.pas' {CaixaMenuView},
  UnCaixaModelo in 'src\UnCaixaModelo.pas' {CaixaModelo: TDataModule},
  UnCaixaRegistroView in 'src\UnCaixaRegistroView.pas' {CaixaRegistroView},
  UsuarioAplicacao in 'src\UsuarioAplicacao.pas',
  UnUsuarioListaRegistrosModelo in 'src\UnUsuarioListaRegistrosModelo.pas' {UsuarioListaRegistrosModelo: TDataModule},
  UnUsuarioListaRegistrosView in 'src\UnUsuarioListaRegistrosView.pas' {UsuarioListaRegistrosView},
  UnUsuarioRegistroModelo in 'src\UnUsuarioRegistroModelo.pas' {UsuarioRegistroModelo: TDataModule},
  UnUsuarioRegistroView in 'src\UnUsuarioRegistroView.pas' {UsuarioRegistroView},
  UnAplicacao in 'src\UnAplicacao.pas',
  UnContasPagarRegistroView in 'src\UnContasPagarRegistroView.pas' {ContasPagarRegistroView},
  UnContasPagarListaRegistrosView in 'src\UnContasPagarListaRegistrosView.pas' {ContasPagarListaRegistrosView},
  UnContasPagarListaRegistrosModelo in 'src\UnContasPagarListaRegistrosModelo.pas' {ContasPagarListaRegistrosModelo: TDataModule},
  UnContasPagarRegistroModelo in 'src\UnContasPagarRegistroModelo.pas' {ContasPagarRegistroModelo: TDataModule},
  ContasPagarAplicacao in 'src\ContasPagarAplicacao.pas',
  UnFornecedorPesquisaModelo in 'src\UnFornecedorPesquisaModelo.pas' {FornecedorPesquisaModelo: TDataModule},
  UnCategoriaPesquisaModelo in 'src\UnCategoriaPesquisaModelo.pas' {CategoriaPesquisaModelo: TDataModule},
  ConectorDeControles in 'src\ConectorDeControles.pas',
  UnCentroDeResultadoPesquisaModelo in 'src\UnCentroDeResultadoPesquisaModelo.pas' {CentroDeResultadoPesquisaModelo: TDataModule},
  SearchUtil in 'src\SearchUtil.pas',
  DataUtil in 'src\DataUtil.pas',
  Util in 'src\Util.pas',
  UnMensagemView in 'src\UnMensagemView.pas' {MensagemView},
  UnMenuView in 'src\UnMenuView.pas' {MenuView},
  UnCentroDeResultadoRegistroView in 'src\UnCentroDeResultadoRegistroView.pas' {CentroDeResultadoRegistroView},
  UnCentroDeResultadoRegistroModelo in 'src\UnCentroDeResultadoRegistroModelo.pas' {CentroDeResultadoRegistroModelo: TDataModule},
  UnCentroDeResultadoListaRegistrosView in 'src\UnCentroDeResultadoListaRegistrosView.pas' {CentroDeResultadoListaRegistrosView},
  UnCentroDeResultadoListaRegistrosModelo in 'src\UnCentroDeResultadoListaRegistrosModelo.pas' {CentroDeResultadoListaRegistrosModelo: TDataModule},
  CentroDeResultadoAplicacao in 'src\CentroDeResultadoAplicacao.pas',
  UnCategoriaRegistroView in 'src\UnCategoriaRegistroView.pas' {CategoriaRegistroView},
  UnCategoriaRegistroModelo in 'src\UnCategoriaRegistroModelo.pas' {CategoriaRegistroModelo: TDataModule},
  CategoriaAplicacao in 'src\CategoriaAplicacao.pas',
  UnMovimentoDeContaCorrenteRegistroView in 'src\UnMovimentoDeContaCorrenteRegistroView.pas' {MovimentoDeContaCorrenteRegistroView},
  UnMovimentoDeContaCorrenteListaRegistrosView in 'src\UnMovimentoDeContaCorrenteListaRegistrosView.pas' {MovimentoDeContaCorrenteListaRegistrosView},
  MovimentoDeContaCorrenteAplicacao in 'src\MovimentoDeContaCorrenteAplicacao.pas',
  UnMovimentoDeContaCorrenteListaRegistrosModelo in 'src\UnMovimentoDeContaCorrenteListaRegistrosModelo.pas' {MovimentoDeContaCorrenteListaRegistrosmodelo: TDataModule},
  UnMovimentoDeContaCorrenteRegistroModelo in 'src\UnMovimentoDeContaCorrenteRegistroModelo.pas' {MovimentoDeContaCorrenteRegistroModelo: TDataModule},
  UnContaCorrenteRegistroView in 'src\UnContaCorrenteRegistroView.pas' {ContaCorrenteRegistroView},
  UnContaCorrenteListaRegistrosView in 'src\UnContaCorrenteListaRegistrosView.pas' {ContaCorrenteListaRegistrosView},
  ContaCorrenteAplicacao in 'src\ContaCorrenteAplicacao.pas',
  UnContaCorrenteRegistroModelo in 'src\UnContaCorrenteRegistroModelo.pas' {ContaCorrenteRegistroModelo: TDataModule},
  UnContaCorrenteListaRegistrosModelo in 'src\UnContaCorrenteListaRegistrosModelo.pas' {ContaCorrenteListaRegistrosModelo: TDataModule},
  UnBancoPesquisaModelo in 'src\UnBancoPesquisaModelo.pas' {BancoPesquisaModelo: TDataModule},
  UnOperacaoDeMovimentoDeContaCorrentePesquisaModelo in 'src\UnOperacaoDeMovimentoDeContaCorrentePesquisaModelo.pas' {OperacaoDeMovimentoDeContaCorrentePesquisaModelo: TDataModule},
  UnContaCorrentePesquisaModelo in 'src\UnContaCorrentePesquisaModelo.pas' {ContaCorrentePesquisaModelo: TDataModule},
  UnFornecedorProdutoView in 'src\UnFornecedorProdutoView.pas' {FornecedorProdutoView},
  UnMovimentoDeContaCorrenteImpressaoView in 'src\UnMovimentoDeContaCorrenteImpressaoView.pas' {MovimentoDeContaCorrenteImpressaoView},
  MovimentoDeCaixaAplicacao in 'src\MovimentoDeCaixaAplicacao.pas',
  UnMovimentoDeCaixaListaRegistrosModelo in 'src\UnMovimentoDeCaixaListaRegistrosModelo.pas' {MovimentoDeCaixaListaRegistrosModelo: TDataModule},
  UnMovimentoDeCaixaListaRegistrosView in 'src\UnMovimentoDeCaixaListaRegistrosView.pas' {MovimentoDeCaixaListaRegistrosView},
  UnMovimentoDeCaixaRegistroModelo in 'src\UnMovimentoDeCaixaRegistroModelo.pas' {MovimentoDeCaixaRegistroModelo: TDataModule},
  UnMovimentoDeCaixaRegistroView in 'src\UnMovimentoDeCaixaRegistroView.pas' {MovimentoDeCaixaRegistroView},
  UnMovimentoDeCaixaImpressaoView in 'src\UnMovimentoDeCaixaImpressaoView.pas' {MovimentoDeCaixaImpressaoView},
  ContasReceberAplicacao in 'src\ContasReceberAplicacao.pas',
  UnContasReceberListaRegistrosModelo in 'src\UnContasReceberListaRegistrosModelo.pas' {ContasReceberListaRegistrosModelo: TDataModule},
  UnContasReceberListaRegistrosView in 'src\UnContasReceberListaRegistrosView.pas' {ContasReceberListaRegistrosView},
  UnContasReceberRegistroModelo in 'src\UnContasReceberRegistroModelo.pas' {ContasReceberRegistroModelo: TDataModule},
  UnContasReceberRegistroView in 'src\UnContasReceberRegistroView.pas' {ContasReceberRegistroView},
  UnClientePesquisaModelo in 'src\UnClientePesquisaModelo.pas' {ClientePesquisaModelo: TDataModule},
  UnOperacaoDeMovimentoDeCaixaPesquisaModelo in 'src\UnOperacaoDeMovimentoDeCaixaPesquisaModelo.pas' {OperacaoDeMovimentoDeCaixaPesquisaModelo: TDataModule},
  RelatorioAplicacao in 'src\RelatorioAplicacao.pas',
  UnRelatorioModelo in 'src\UnRelatorioModelo.pas' {RelatorioModelo: TDataModule},
  UnRelatorioView in 'src\UnRelatorioView.pas' {RelatorioView},
  Relatorios in 'src\Relatorios.pas',
  UnFabricaDeModelos in 'src\UnFabricaDeModelos.pas',
  Dominio in 'src\Dominio.pas',
  UnRelatorioTemplate in 'src\UnRelatorioTemplate.pas' {RelatorioTemplateView},
  UnFabricaDeDominios in 'src\UnFabricaDeDominios.pas' {FabricaDeDominio: TDataModule},
  UnResultadoGeralMesRelatorio in 'src\UnResultadoGeralMesRelatorio.pas' {ResultadoGeralMesRelatorio},
  UnResultadoGeralAnoRelatorio in 'src\UnResultadoGeralAnoRelatorio.pas' {ResultadoGeralAnoRelatorio},
  FechamentoDeContaAplicacao in 'src\FechamentoDeContaAplicacao.pas',
  UnFechamentoDeContaModelo in 'src\UnFechamentoDeContaModelo.pas' {FechamentoDeContaModelo: TDataModule},
  UnFechamentoDeContaView in 'src\UnFechamentoDeContaView.pas' {FechamentoDeContaView};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Petisco - Centro de Controle';
  Application.CreateForm(TPetiscoDashBoardView, PetiscoDashBoardView);
  Application.CreateForm(TFechamentoDeContaModelo, FechamentoDeContaModelo);
  Application.CreateForm(TFechamentoDeContaView, FechamentoDeContaView);
  Application.Run;
end.
